---
title: "plotly"
author: "Sophia Chkonia"
date: "2022-10-25"
output: html_document


---

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


get data

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>% 
  mutate(rating = review_scores_location/2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, price, room_type, 
    lat, long, rating
  ) %>% 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  ) %>% 
  drop_na(rating)
  
```

let's make a scatterplot

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price:", price)
  ) %>% 
  plot_ly(
    x = ~lat,
    y = ~ long,
    color = ~price,
    type = "scatter", mode = "markers",
    alpha = .5,
    text = ~text_label
  )
```

boxplots: 

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    y = ~ price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```



bar plot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```


## ggplotply...

```{r}
gg_scatterplot = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(gg_scatterplot)
```





